#!/bin/bash

# clang -E -DCTGUI_EXPORTS -DTGUI_DYNAMIC -DTGUI_NO_DEPRECATED_WARNINGS -I../build/_deps/csfml-src/include -I../build/_deps/ctgui-src/include -I../build/_deps/ctgui-src/src -I../build/_deps/tgui-src/include -I../build/_deps/sfml-src/include all.c -o merged.c

cd "$(dirname "$0")"

function count_lines {
  echo "$1" | wc -l | xargs
}

echo "
#include <CTGUI/Backend/CSFML-Graphics.h>
#include <CTGUI/CTGUI.h>

// Below files are not included in CTGUI.h
#include <CTGUI/Renderers/CheckBoxRenderer.h>
#include <CTGUI/Renderers/PanelListBoxRenderer.h>
#include <CTGUI/Renderers/SeparatorLineRenderer.h>
#include <CTGUI/ScrollbarAccessor.h>
#include <CTGUI/Widgets/GrowHorizontalLayout.h>
#include <CTGUI/Widgets/GrowVerticalLayout.h>
#include <CTGUI/Widgets/PanelListBox.h>
#include <CTGUI/Widgets/RichTextLabel.h>
#include <CTGUI/Widgets/SeparatorLine.h>
" | 
clang \
  -E -DCTGUI_EXPORTS -DTGUI_DYNAMIC -DTGUI_NO_DEPRECATED_WARNINGS \
  -I../build/_deps/csfml-src/include \
  -I../build/_deps/ctgui-src/include \
  -I../build/_deps/ctgui-src/src \
  -I../build/_deps/tgui-src/include \
  -I../build/_deps/sfml-src/include - |
clang -Xclang -ast-dump=json -fsyntax-only -w -x c - |
deno --allow-read --allow-write symbolGenerator.ts |
deno fmt - > ctguiSymbols.ts

mv ctguiSymbols.ts ../src/ctguiSymbols.ts

# Availability status of the API
deno --allow-read --allow-write externSearch.ts

unavailable_list=`comm -13 available-list.txt extern-list.txt`
unavailable_count=`count_lines "$unavailable_list"`
available_count=`count_lines "$(cat available-list.txt)"`
extern_count=`count_lines "$(cat extern-list.txt)"`

echo "EXTERN functions: $extern_count
AVAILABLE functions: $available_count"

echo "
Following $unavailable_count functions are marked extern, but are excluded:
$unavailable_list"

rm available-list.txt extern-list.txt