#!/bin/bash

mode=$1 # Debug | Release
arch=${2:-"arm64"} # arm64 | x86_64

if [[ "$OS" == *Windows* ]]; then
    if [[ "$mode" == "Debug" ]]; then
        libname="ctgui-d-1.dll"
    else
        libname="ctgui-1.dll"
    fi

    cmake --build build --config $mode

    cp build/_deps/ctgui-build/src/CTGUI/$libname build/ctgui-ext.dll
else
    if [[ "$mode" == "Debug" ]]; then
        libname="libctgui-d.1.8.0.dylib"
    else
        libname="libctgui.1.8.0.dylib"
    fi

    outname="libctgui-ext.dylib"

    if [[ "$arch" == "x86_64" ]]; then
        outname="libctgui-ext-x86_64.dylib"
    fi

    cmake --build build --config $mode

    cp build/_deps/ctgui-build/src/CTGUI/$libname build/$outname
fi
